FROM debian:12-slim
ENV DEBIAN_FRONTEND=noninteractive

# Install OpenSSH server, Git, and dependencies for NodeSource
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      openssh-server ca-certificates acl \
      git \
      curl gnupg \
 && mkdir -p /etc/apt/keyrings \
 && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
      | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
 && NODE_MAJOR=22 \
 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" \
      > /etc/apt/sources.list.d/nodesource.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends nodejs \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir -p /var/run/sshd

# Global config:
# - allow password login (for non-root users)
# - disable challenge-response
RUN sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config \
 && sed -i 's/^#\?ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config \
 && sed -i 's/^#\?UsePAM.*/UsePAM yes/' /etc/ssh/sshd_config

# SSH rules specifically for root
# - root can only login via key (no password)
RUN echo "" >> /etc/ssh/sshd_config \
 && echo "StrictModes no" >> /etc/ssh/sshd_config \
 && echo "" >> /etc/ssh/sshd_config \
 && echo "Match User root" >> /etc/ssh/sshd_config \
 && echo "    PermitRootLogin prohibit-password" >> /etc/ssh/sshd_config \
 && echo "    PasswordAuthentication no" >> /etc/ssh/sshd_config

# Ensure .ssh directory exists and has correct permissions
RUN mkdir -p /root/.ssh \
 && chmod 700 /root/.ssh

RUN groupadd -g 1001 appsgroup

EXPOSE 22

RUN echo "#!/bin/bash\nchown root:root /root/.ssh/authorized_keys && chmod 600 /root/.ssh/authorized_keys && chmod -R 751 /users/ && chmod -R g+s /users/apps && setfacl -R -m u::rwx,g::rwx,o::--x /users/apps && setfacl -R -d -m u::rwx,g::rwx,o::--x /users/apps && /usr/sbin/sshd -D" > /start.sh
RUN chmod 755 /start.sh

CMD ["/start.sh"]